### PR TITLE
Expose Country only when it's safe

### PR DESCRIPTION
**Pull request by ixti**

### CODE REVIEW

**Comment by rposborne** [comment]
I think I would prefer to raise an error here since we already have facilities to prevent this name conflict, then have it fail silently.

**Comment by ixti** [comment]
Either way - I'm OK. Just wanted to avoid `:require => ...` in Gemfile ;))

**Comment by kennethkalmer** [comment]
I'm bumping into this issue where I already have a `Country` global, and I thought to open a similar PR. However, I thought instead of magically defining a `Country` class, why not explicitly `require "countries/global"` if you need the old behavior?

**Comment by rposborne** [comment]
@kennethkalmer I like the idea of just switching the default behavior vs dynamically detecting if we are going to conflict.

**Comment by rposborne** [comment]
I have a PR using @kennethkalmer suggestion, here #285

**Comment by ixti** [comment]
Closed in favor of #285

**Pull request closed without merging**
