### PR TITLE
Lithuania adopted the Euro on 2015-01-01

### PR DESCRIPTION
**Pull request by philippbosch**
http://en.wikipedia.org/wiki/Lithuania_and_the_euro

### CODE REVIEW

**Comment by oliverklee** [comment]
:+1:

**Comment by adrianmacneil** [comment]
:+1:

**Comment by mhluska** [comment]
:+1:

**Comment by adrianmacneil** [comment]
ping @hexorx

**Comment by TomasAchmedovas** [comment]
:+1:

**Comment by adrianmacneil** [comment]
\o/

**Pull request merged**
