### PR TITLE
Update gemspec: i18n_data 0.11.0

### PR DESCRIPTION
**Pull request by masawo**
- update gemspec: bump `i18n_data`
- run `rake update_cache`

### CODE REVIEW

**Comment by rposborne** [comment]
Thanks for this.  Lets redo the last commit against master to resolve conflicts in the cache.

**Comment by masawo** [comment]
I resolved conflicts. Thanks.

**Review by pmor — APPROVED** [review]

**Comment by jaredbeck** [comment]
Conflicts are resolved, and changes are approved. Looks like this is ready for merge @pmor @rposborne @hexorx

**Comment by rposborne** [comment]
Merged, and released as v3.1.0 thanks @masawo and @jaredbeck

**Pull request merged**
