### PR TITLE
[fix] correction of countries' names in locale br

### PR DESCRIPTION
**Pull request by RamonHossein**

### CODE REVIEW

**Comment by RamonHossein** [comment]
@hexorx check it please.

**Comment by rposborne** [comment]
@RamonHossein It appears you modified a cache file.  This will get run over during our build process.  Can you please add any corrections to our overall translations in this file. https://github.com/hexorx/countries/blob/master/lib/countries/data/translation_corrections.yaml

**Comment by rposborne** [comment]
@RamonHossein Just a heads up, we rebuilt our cache so these merged in changes are no longer in master. Can I help get the fixes in the translations_correction.yaml file?

**Comment by RamonHossein** [comment]
Thanks for it. @rposborne can help me with the translations_correction.yml file.

**Pull request merged**
