### PR TITLE
Allow searching by translated_names, which are once again cached in gem.

### PR DESCRIPTION
**Pull request by rposborne**

### CODE REVIEW

**Comment by rposborne** [comment]
This is an attempt to have a the best of both worlds. i18n_data structure is slightly different, locale first vs country first.  This adds a rake task to cache it's data in country first format and store it in gem.   We are once again very close to the previous performance.   

@stayhero , @hexorx could you take a look at this?

See #223 
See #226

**Comment by jernejstrasner** [comment]
This is awesome. Just what I need.

**Comment by stayhero** [comment]
I tried to use country_select with your branch burningpony:faster-search-by-name and get this error when trying to open rails console:

```
Users/christian/dev/rails/gems/countries/lib/iso3166.rb:8:in `<top (required)>': uninitialized constant ISO3166::Country::Names (NameError)
	from /Users/christian/dev/rails/gems/country_select/lib/country_select.rb:3:in `require'
	from /Users/christian/dev/rails/gems/country_select/lib/country_select.rb:3:in `<top (required)>'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `require'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `each'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `each'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `require'
	from /Users/christian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler.rb:133:in `require'
```

I assume it's because you removed line 7 in lib/country/country.rb:

```Names = I18nData.countries.values.sort_by { |d| d[0] }```?

**Comment by rposborne** [comment]
@jernejstrasner This has been reverted... basically the quality of some of our translations makes this worthless.

**Pull request merged**
