### PR TITLE
added config for Kosovo

### PR DESCRIPTION
**Pull request by hex0cter**

### CODE REVIEW

**Comment by rposborne** [comment]
@hex0cter Kosovo is classified as a "Disputed" country and is not recognized by the ISO specification which this repo attempts to follow.   I am highly interested in adding a "Disputed country" mode so we do not have to make this type of geopolitical stances.  I will leave this Pull Request open but in limbo until we determine a way to approach storing these disputed countries.

**Comment by gurix** [comment]
We are using the gem country_select that in turn uses countries gem. Recently we had a complaint why Kosovo is not on the list. I would highly appriciate a dispute mode but and would implement this in the country_select gem as option. By default it should be visible as disputed which can disabled.

**Comment by arianitg** [comment]
@rposborne :+1:  for this PR

**Comment by nickcoyne** [comment]
Another vote for a "disputed country" mode. We have users wanting to select country Kosovo in our forms.

**Comment by pmor** [comment]
Kosovo continues not to be present in the ISO data set, so I'm closing this for the time being.

**Comment by henrik** [comment]
FYI if anyone else wants to add this, do e.g. this (perhaps in `config/initializers/countries.rb` if in a Rails project):

```
ISO3166::Data.register(
   alpha2: "XK",
   alpha3: "XKX",
  name: "Kosovo",
  currency: "EUR",
  translations: {
    "en" => "Kosovo",
  },
)
```

with whatever data you need. Refer to [the docs](https://github.com/hexorx/countries#loading-custom-data) for details.

**Comment by kg-currenxie** [comment]
How would you add bounds?

I've tried

```
ISO3166::Data.register(
  alpha2: 'XK',
  alpha3: 'XKX',
  name: 'Kosovo',
  currency_code: 'EUR',
  min_longitude: '-70.066667',
  min_latitude: '12.416667',
  max_longitude: '-69.85',
  max_latitude: '12.616667',
  translations: {
    en: 'Kosovo'
  }
)
```

I'm getting errors:

```
irb(main):001:0> c = ISO3166::Country.find_country_by_alpha2('xk')
irb(main):002:0> c.data
=> {"alpha2"=>"XK", "alpha3"=>"XKX", "name"=>"Kosovo", "currency_code"=>"EUR", "min_longitude"=>"-70.066667", "min_latitude"=>"12.416667", "max_longitude"=>"-69.85", "max_latitude"=>"12.616667", "translations"=>{:en=>"Kosovo"}}
irb(main):003:0> c.min_latitude
Traceback (most recent call last):
        1: from (irb):3
NoMethodError (undefined method `[]' for nil:NilClass)
```

**Comment by pmor** [comment]
@kg-currenxie Try this:

```ruby
ISO3166::Data.register(
  alpha2: "XK",
  alpha3: "XKX",
  name: "Kosovo",
  currency: "EUR",
  translations: {
    "en" => "Kosovo",
  },
  geo: {
    min_longitude: '-70.066667',
    min_latitude: '12.416667',
    max_longitude: '-69.85',
    max_latitude: '12.616667'
  }
)
```

**Comment by pmor** [comment]
The geo data hash is not being properly parsed in `ISO3166::Data.register`. The linked PR addresses it.

**Comment by Gerst20051** [comment]
If you are using an older version of this library you can update the data cache like this:

```ruby
# update country data
ISO3166::Country::Data.delete('AN')
ISO3166::Country::Data['XK'] = {
  'alpha2' => 'XK',
  'alpha3' => 'XKX',
  'name' => 'Kosovo',
  'currency' => 'EUR',
  'translations' => {
    'en' => 'Kosovo'
  }
}
# use an optimized version of the code from the countries library
# https://github.com/countries/countries/blob/v0.8.9/lib/countries/country.rb#L4
ISO3166::Country::Data = ISO3166::Country::Data.sort.to_h
ISO3166::Country::Names = ISO3166::Country::Data.map { |k,v| [v['name'], k] }
ISO3166::Country::Names.sort!
ISO3166::Country::NameIndex = Hash[ISO3166::Country::Names]
```

**Pull request closed without merging**
