### PR TITLE
added NPN code after country code NANP

### PR DESCRIPTION
**Pull request by maomaoZH**
added 19 countries NPN code

### CODE REVIEW

**Comment by rposborne** [comment]
This appears to be breaking previous implementations, but this we do want this data.   Can we add a new field for this code? or for the combination?

**Comment by maomaoZH** [comment]
I can do another pull request for this data.  What field name do you suggest?

**Comment by rposborne** [comment]
@maomaoZH maybe something like `nanp_area_code` or `nanp_prefix`

**Comment by maomaoZH** [comment]
ok. will do it.

**Pull request merged**
