### PR TITLE
Add Documentation for Country Code Emoji Flags

### PR DESCRIPTION
**Pull request by contrepoint**
As mentioned in [issue 378](https://github.com/hexorx/countries/issues/378)

### CODE REVIEW

**Comment by rposborne** [comment]
Thanks!

**Comment by bbnnt** [comment]
Hello, sorry to bother; I tried what's shown in the README, but can't get anything but a `undefined method`

I have this in my gemfile : `gem 'countries', :require => 'countries/global'`

And the Gemfile.lock show the following : `countries (1.2.5)` 

I did a `gem update countries`

Am I missing something ?

**Comment by rposborne** [comment]
@bbnnt The docs that are showing a for a pre release version of countries, at the 2.0.0.

**Comment by contrepoint** [comment]
@rposborne should I raise another PR to mention this or will 2.0.0 be released soon? don't want people to be confused.

**Pull request merged**
