### PR TITLE
Updated Spanish and added Catalan language

### PR DESCRIPTION
**Pull request by jordigg**
Updated missing Spanish translations and added Catalan language for all the entries.

### CODE REVIEW

**Comment by jordigg** [comment]
Failed because I have added the Catalan and missing Spanish translations to the "names" tag.

**Comment by rposborne** [comment]
Please update the specs that you break even if they are trivial.  :+1: Thanks!

**Comment by jordigg** [comment]
@rposborne fixed specs as requested but still failing on Shippable. Can't see why, all test pass on my local environment. I'm new with Ruby so sorry about my questions :smile:

**Comment by rposborne** [comment]
@jordigg we changed how we handle translation and are now depending on a gem call i1l8n_data which has complete translations for almost every language.  Thank you for your contributions and keep up the learning!

**Pull request closed without merging**
