### PR TITLE
[CI] Test against Ruby 2.1 and 2.5

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by rposborne** [comment]
@nicolasleger I love 2.5,  but 2.1 is end of life, and most likely should not be included.

**Comment by nicolasleger** [comment]
@rposborne Hello, should I remove `1.9.3` and `2.2` (soon EOL) too?

**Comment by rposborne** [comment]
remove 2.2, we were keeping 1.9.3 around with allow-fail for some legacy projects.

**Comment by nicolasleger** [comment]
Ok, done

**Comment by rposborne** [comment]
@nicolasleger Thanks for this!

**Pull request merged**
