### PR TITLE
Add country code 672 to HM

### PR DESCRIPTION
**Pull request by wongyouth**
Refer to https://www.iso.org/obp/ui/#search
'Heard Island and McDonald Islands' get a country code of 334

**UPDATE**: actually, the country code is 672.

### CODE REVIEW

**Comment by pmor** [comment]
@rposborne

**Comment by siklodi-mariusz** [comment]
@wongyouth I'm also having issues with my project because of the missing country code of _Heard Island and McDonald Islands_. Unfortunately, the code you added is not the correct one. 334 is referring to the assigned country number and it can be found here:
https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/HM.yaml#L14

The `country_code` yaml key is actually referring to the ISD (International Subscriber Dialing) phone country code. I checked multiple countries and it seems that this is the case. For example, I live in Romania, and our code is 40 and this is what Romania has set as `country_code` here:
https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/RO.yaml#L11

So in the case of _Heard Island and McDonald Islands_ the ISD seems to be 672.
Here are a few sources I found online about this:
https://www.goldenchennai.com/isd-code/isd-code-for-heard-island-and-mcdonald-islands/
https://46elks.com/kb/country-codes
https://en.wikipedia.org/wiki/List_of_country_calling_codes  (The good old Wikipedia 😄 )

So do you think you could make this change?

**Comment by siklodi-mariusz** [comment]
Also for anyone stumbling upon this and looking for a quick fix. 

This is what I did in my project (Rails):

```ruby
# config/initializers/countries.rb

ISO3166::Data.register(
  ISO3166::Country.find_country_by_alpha2('HM').data.with_indifferent_access.merge(country_code: '672')
)

```

**Comment by wongyouth** [comment]
Thanks @siklodi-mariusz, you are right. I'm glad to change this.

**Pull request merged**
