### PR TITLE
🇬🇧🇪🇺 Britain leaves the EU and EEA

### PR DESCRIPTION
**Pull request by seanhandley**
For when the day actually comes 😢

### CODE REVIEW

**Comment by rposborne** [comment]
@seanhandley Is there a day that this is supposed to happen? (I can't tolerate looking at the news these days)

**Comment by seanhandley** [comment]
March 29th 2019 is the absolute limit for all agreements to be finalised. Even if they're not finalised by then, by the terms of Article 50 Britain will officially be out of the union and the EEA.

**Comment by pmor** [comment]
Looks like January 31st 2020 it is.

The Brexit agreement was signed a few hours ago and the final vote in the European Parliament  should be on January 29th.

**Comment by seanhandley** [comment]
Wow, nearly two years later and it's time to merge this.

What an agonising and upsetting time it's been. So long, EU 💔

**Pull request merged**
