### PR TITLE
Update German VAT Rate with temporary reduction until the end of 2020

### LINKED ISSUE #637: Temporary German VAT rate (16%) from July 1st to December 31st, 2020
Hello, I just noticed the rate for Germany have been temporarily reduced 3 days ago and for the next 6 months: https://taxfoundation.org/germany-temporary-vat-rates-cut/#:~:text=The%20standard%20VAT%20rate%20will,reading%20materials%2C%20and%20cultural%20events.

I don't have much time to setup the project and write a PR now but I may be able to do it later if nobody does it since then ;)

### PR DESCRIPTION
**Pull request by pmor**
Closes #637

### CODE REVIEW

**Comment by pmor** [comment]
@rposborne We're not too far from the end of the year, but given the way things are, I wouldn't be surprised to see this reduction extended, so maybe it still makes sense to merge this?

**Comment by jarthod** [comment]
Agreed ;)

**Comment by jarthod** [comment]
Apparently the lower rate has not been extended: https://www.avalara.com/vatlive/en/vat-news/german-vat-rate-returns-to-19--1-jan-2021.html so I guess we can abandon this ^^

**Comment by pmor** [comment]
Closing since this is no longer applicable.

**Pull request closed without merging**
