### PR TITLE
Update and fix Poland subdivisions data

### PR DESCRIPTION
**Pull request by skarlcf**

### CODE REVIEW

**Comment by rposborne** [comment]
Could you please rebase this onto master.

**Comment by rposborne** [comment]
Could you provide a source for the subdivisions switch to a numerical format.  The [last newsletter for ISO](  http://www.iso.org/iso/iso_3166-2_newsletter_ii-3_2011-12-13.pdf ) page 59, makes no mention of this.

**Comment by cllns** [comment]
Another source showing that no change to numbers has been made: https://www.iso.org/obp/ui/#iso:code:3166:PL (and it seems that site is kept up to date, since it had a change for Cuba from 2014)

**Comment by skarlcf** [comment]
@rposborne My mistake. I use no ISO codes and I will fix it. (source: http://pl.wikipedia.org/wiki/Wojew%C3%B3dztwo#Stan_aktualny_.E2.80.93_16_wojew.C3.B3dztw)

**Pull request merged**
