### PR TITLE
Add subdivision names with codes

### LINKED ISSUE #479: all_subdivisions_names_with_codes
Hello,
First, thank you for this beneficial gem.
In our project, we needed to have a select list for countries that populates another list of subdivisions. So basically when you choose a country, the subdivision list gets updated accordingly. 
We needed to add a method called `all_subdivisions_names_with_codes(locale)` on a `Country`, just similar to `all_names_with_codes(locale)`. It helps in implementing the described kind of behavior. I find this a popular use case, thus, I'm wondering if it's desirable to have this feature built in the library. 
Should I PR?

### PR DESCRIPTION
**Pull request by md-hamed**
Resolves #479.

### CODE REVIEW

**Comment by md-hamed** [comment]
@rposborne 
* Please note that I haven't used `html_safe` here for the name of the subdivision as done in `all_names_with_codes` as I see no reason for using it in the first place. Please confirm that this is true.
* There are some subdivisions with no name. Is there a plan to resolve this by adding the missing names to the subdivision data or should I fallback to the English translation?

**Comment by md-hamed** [comment]
@rposborne any updates?

**Comment by rposborne** [comment]
@md-hamed Sorry I totally missed your pr.  I think neglecting html_safe is fine, and I am not totally sure why it is there either.

**Comment by rposborne** [comment]
@md-hamed 2.1.3 released which includes this change

**Comment by md-hamed** [comment]
@rposborne Glad to hear that! Thanks Russell

**Pull request merged**
