### PR TITLE
Adding TimeZone Support

### PR DESCRIPTION
**Pull request by rposborne**
This is a first draft on optional timezone support.   I could be convinced either way if this should be included by default.

### CODE REVIEW

**Comment by dgilperez** [comment]
:clap:

**Comment by esaborit4code** [comment]
As this gem doesn't have any optional feature or config yet, I would add timezones by default as long as it doesn't add any performance issues or some kind of overriding conflict.

Anyway, I don't know the codebase deeply, so consider this just as an opinion.

**Comment by rposborne** [comment]
@esaborit4code We are going to be adding a config come 2.0. Which we will wrap this into.  I want optional loading of all data, so we can keep our memory usage down so we can be as useful as possible across the board.

**Comment by rposborne** [comment]
Closing in favor of #317,   Timezones will be extended by default, but tzinfo is not a dependency.

**Pull request closed without merging**
