### PR TITLE
add decimal coordinate for each country

### PR DESCRIPTION
**Pull request by jabawack81**
I've added the decimal latitude and longitude of each country so it can be used as data source for http://jvectormap.com/

### CODE REVIEW

**Comment by rposborne** [comment]
Looks like you used camelcase for this,  could you please use Ruby style snake case.

**Comment by jabawack81** [comment]
My bad, renamed.

**Comment by rposborne** [comment]
@jabawack81 we just did a reasonable amount of restructuring data,  any chance you could move this over to the new data format? Each country has a ```lib/data/countries/US.yaml``` one file per country

**Comment by rposborne** [comment]
Here is a rake task I used on a few PR's 
``` ruby
task :pull_new_keys_from_old_file do
  require 'yaml'
  countries = YAML.load_file File.join(File.dirname(__FILE__),  'countries.yaml')
  country_list = []
  countries.each do |cc, _data|
    keys = [ 'min_longitude',
            'min_latitude',
            'max_longitude',
            'max_latitude'
           ]
    country_data = YAML.load_file File.join(File.dirname(__FILE__), 'lib', 'data','countries', "#{cc}.yaml")
    keys.each do |key|
      country_data[cc][key] = countries[cc][key]
    end
    File.open(File.join(File.dirname(__FILE__), 'lib', 'data', 'countries', "#{cc}.yaml"), 'w') do |h|
      h.write(country_data.to_yaml)
    end
  end
end
```
Just put the keys you want to pull in the keys array, and have your old countries file at the root of the rep

**Comment by jabawack81** [comment]
thi PR can be deleted I've made a new one with the new structure.

Jaba

**Pull request closed without merging**
